print('========================================')
lista = []
print('Lista actual', lista[:])
print('========================================')
print ('Opciones')
print ('1.- AGREGAR NOMBRE')
print ('2.- SALIR')
print('3.- BORRAR')
agregar = int(input('Ingresa tu opcion: '));
if agregar > 3 or agregar < 1:
    print('Haz ingresado la opcion incorrecta')
while agregar == 1:    
    nombre=str(input("ingresa tu nombre: "));
    print('========================================')
    lista.append(nombre)
    print('Lista actual', lista[:])
    print('========================================')
    print ('Opciones')
    print ('1.- AGREGAR NOMBRE')
    print ('2.- SALIR')
    print('3.- BORRAR ULTIMO NOMBRE INGERSADO')
    print('========================================')
    agregar = int(input('Ingresa tu opcion: '))
while agregar == 3:
    lista.pop()    
    print('Nombre borrado')
    print('Lista actual', lista[:])
    print('========================================')
    print('Deceas seguir?')
    print('========================================')
    print ('Opciones')
    print ('1.- AGREGAR NOMBRE')
    print ('2.- SALIR')
    print('3.- BORRAR NOMBRE')
    print('========================================')
    agregar = int(input('Ingresa tu opcion: '))
if agregar == 2:
    print('========================================')
    print ('Que tengas buen día!!!')  
    print('========================================')
